### ISSUE TITLE
run dev:client fails on Node 18, Windows

### ISSUE THREAD

**Issue by jfgreffier** [kentcdodds/jest-cypress-react-babel-webpack#50]
Running run dev on Node.js 18 fails, it seems to be linked with SSL

```bash
> npm run dev

> calculator@2.0.0 dev:client
> webpack serve --mode=development

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Testing JavaScript\jest-cypress-react-babel-webpack\public
i ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\Testing JavaScript\jest-cypress-react-babel-webpack\node_modules\webpack\lib\util\createHash.js:138:18)    
    at BulkUpdateDecorator.update (C:\Testing JavaScript\jest-cypress-react-babel-webpack\node_modules\webpack\lib\util\createHash.js:44:50)
    at NormalModule._initBuildHash (C:\Testing JavaScript\jest-cypress-react-babel-webpack\node_modules\webpack\lib\NormalModule.js:737:17)
    at handleParseResult (C:\Testing JavaScript\jest-cypress-react-babel-webpack\node_modules\webpack\lib\NormalModule.js:801:10)
    at C:\Testing JavaScript\jest-cypress-react-babel-webpack\node_modules\webpack\lib\NormalModule.js:854:4
    at processResult (C:\Testing JavaScript\jest-cypress-react-babel-webpack\node_modules\webpack\lib\NormalModule.js:625:11)
    at C:\Testing JavaScript\jest-cypress-react-babel-webpack\node_modules\webpack\lib\NormalModule.js:676:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.1
ERROR: "dev:client" exited with 1.
```

**Comment by jfgreffier** [comment]
Seems to be the same as #49
